In [1]:
import numpy as np


In [2]:
mat1 = np.array([[1,2],[3,4]])

In [3]:
mat2 = np.array([[3,4],[1,2]])

In [4]:
print(mat1 @ mat2)

[[ 5  8]
 [13 20]]


In [5]:
mat1.shape

(2, 2)

In [6]:
np.transpose(mat1)

array([[1, 3],
       [2, 4]])

In [8]:
2* mat1

array([[2, 4],
       [6, 8]])

In [9]:
mat1 + mat2

array([[4, 6],
       [4, 6]])