# Linear Algebra - Practice Exercises

Work through these exercises to build muscle memory with NumPy.

**How to use:**
1. Read the problem
2. Write your code where it says `# YOUR CODE HERE`
3. Run the cell
4. Check the solution below if stuck

In [1]:
import numpy as np

---
## Section 1: Vectors

### Exercise 1: Create a vector and inspect it

Create a vector `[4, 7, 2, 9]` and print its shape and number of dimensions.

**Hint:** Use `np.array()`, `.shape`, `.ndim`

In [2]:
# YOUR CODE HERE


# Expected output:
# Vector: [4 7 2 9]
# Shape: (4,)
# Dimensions: 1

### Solution

```python
v = np.array([4, 7, 2, 9])
print(f"Vector: {v}")
print(f"Shape: {v.shape}")
print(f"Dimensions: {v.ndim}")
```

---
### Exercise 2: Vector addition

Add vectors `a = [1, 2, 3]` and `b = [4, 5, 6]`, then verify the result equals `[5, 7, 9]`.

**Hint:** Use `+` operator and `np.array_equal()`

In [3]:
# YOUR CODE HERE


# Expected output:
# a + b = [5 7 9]
# Correct: True

### Solution

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(f"a + b = {result}")
print(f"Correct: {np.array_equal(result, [5, 7, 9])}")
```

---
### Exercise 3: Scalar multiplication

Multiply vector `v = [3, 4]` by scalar `5`. Verify the result.

**Hint:** Just use `5 * v`

In [4]:
# YOUR CODE HERE


# Expected output:
# 5 * v = [15 20]
# Correct: True

### Solution

```python
v = np.array([3, 4])
result = 5 * v
print(f"5 * v = {result}")
print(f"Correct: {np.array_equal(result, [15, 20])}")
```

---
### Exercise 4: Dot product

Compute the dot product of `a = [1, 2, 3]` and `b = [4, 5, 6]`.
Verify it equals `32` (because 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32).

**Hint:** Use `np.dot(a, b)`

In [5]:
# YOUR CODE HERE


# Expected output:
# Dot product: 32
# Correct: True

### Solution

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)
print(f"Dot product: {dot}")
print(f"Correct: {dot == 32}")
```

---
### Exercise 5: Vector length (norm)

Find the length of vector `v = [3, 4]`. Verify it equals `5.0`.

(This is the 3-4-5 right triangle! sqrt(9+16) = sqrt(25) = 5)

**Hint:** Use `np.linalg.norm(v)`

In [6]:
# YOUR CODE HERE


# Expected output:
# Length: 5.0
# Correct: True

### Solution

```python
v = np.array([3, 4])
length = np.linalg.norm(v)
print(f"Length: {length}")
print(f"Correct: {length == 5.0}")
```

---
## Section 2: Matrices

### Exercise 6: Create a matrix and inspect shape

Create a 3x3 matrix: `[[1,2,3],[4,5,6],[7,8,9]]` and print its shape.

**Hint:** Use `np.array()` with nested lists

In [7]:
# YOUR CODE HERE


# Expected output:
# Matrix:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# Shape: (3, 3)

### Solution

```python
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix:\n{M}")
print(f"Shape: {M.shape}")
```

---
### Exercise 7: Identity matrix

Create a 4x4 identity matrix using `np.eye()`.

**Hint:** `np.eye(n)` creates an nxn identity matrix

In [8]:
# YOUR CODE HERE


# Expected output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

### Solution

```python
I = np.eye(4)
print(I)
```

---
### Exercise 8: Matrix-vector multiplication

Multiply matrix `A = [[1,2],[3,4]]` by vector `v = [1, 0]`.
The result should be `[1, 3]` (which is the first column of A).

**Hint:** Use `@` operator: `A @ v`

In [9]:
# YOUR CODE HERE


# Expected output:
# A @ v = [1 3]
# Correct: True

### Solution

```python
A = np.array([[1,2],[3,4]])
v = np.array([1, 0])
result = A @ v
print(f"A @ v = {result}")
print(f"Correct: {np.array_equal(result, [1, 3])}")
```

---
### Exercise 9: Matrix-matrix multiplication

Compute `A @ B` where:
- `A = [[1,2],[3,4]]`
- `B = [[5,6],[7,8]]`

**Hint:** Use `@` operator. Remember: row of A times column of B.

In [10]:
# YOUR CODE HERE


# Expected output:
# A @ B =
# [[19 22]
#  [43 50]]

### Solution

```python
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(f"A @ B =\n{A @ B}")
```

---
### Exercise 10: Transpose a matrix

Transpose `M = [[1,2,3],[4,5,6]]`. Verify shape changes from `(2,3)` to `(3,2)`.

**Hint:** Use `M.T` or `np.transpose(M)`

In [11]:
# YOUR CODE HERE


# Expected output:
# Original shape: (2, 3)
# Transposed shape: (3, 2)
# Transposed:
# [[1 4]
#  [2 5]
#  [3 6]]

### Solution

```python
M = np.array([[1,2,3],[4,5,6]])
print(f"Original shape: {M.shape}")
print(f"Transposed shape: {M.T.shape}")
print(f"Transposed:\n{M.T}")
```

---
## Section 3: Determinant & Inverse

### Exercise 11: Compute determinant

Compute the determinant of `A = [[1,2],[3,4]]`. It should equal `-2.0`.

Formula: ad - bc = 1*4 - 2*3 = 4 - 6 = -2

**Hint:** Use `np.linalg.det(A)`

In [12]:
# YOUR CODE HERE


# Expected output:
# Determinant: -2.0
# Correct: True

### Solution

```python
A = np.array([[1,2],[3,4]])
det = np.linalg.det(A)
print(f"Determinant: {det}")
print(f"Correct: {det == -2.0}")
```

---
### Exercise 12: Matrix inverse

Invert `A = [[4,7],[2,6]]`, then verify `A @ A_inv = Identity`.

**Hint:** Use `np.linalg.inv(A)`, check with `np.allclose()`

In [13]:
# YOUR CODE HERE


# Expected output:
# A @ A_inv =
# [[1. 0.]
#  [0. 1.]]
# Is identity: True

### Solution

```python
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
product = A @ A_inv
print(f"A @ A_inv =\n{product.round(10)}")
print(f"Is identity: {np.allclose(product, np.eye(2))}")
```

---
### Exercise 13: Singular matrix (not invertible)

Try to invert `C = [[1,2],[2,4]]`. What happens? Why?

First check the determinant. If det=0, the matrix is **singular** (not invertible).

**Hint:** Use try/except with `np.linalg.inv()`

In [14]:
# YOUR CODE HERE


# Expected output:
# det = 0.0
# Matrix is singular! Cannot invert.

### Solution

```python
C = np.array([[1,2],[2,4]])
det = np.linalg.det(C)
print(f"det = {det}")

if abs(det) < 1e-10:
    print("Matrix is singular! Cannot invert.")
    print("Row 2 = 2 * Row 1, so information was lost.")
else:
    print(np.linalg.inv(C))
```

---
### Exercise 14: Solve a linear system

Solve the system:
```
3x + y = 9
 x + 2y = 8
```

In matrix form: `A @ [x, y] = b`

**Hint:** Use `np.linalg.solve(A, b)`

In [15]:
# YOUR CODE HERE


# Expected output:
# Solution: x=2.0, y=3.0
# Verify 3x+y = 9.0
# Verify x+2y = 8.0

### Solution

```python
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(f"Solution: x={x[0]:.1f}, y={x[1]:.1f}")
print(f"Verify 3x+y = {3*x[0] + x[1]:.1f}")
print(f"Verify x+2y = {x[0] + 2*x[1]:.1f}")
```

---
## Section 4: Eigen

### Exercise 15: Find eigenvalues

Find the eigenvalues of `A = [[2,1],[1,2]]`. They should be `[3, 1]`.

**Think:** Why 3 and 1? The matrix stretches in one direction by 3, another by 1.

**Hint:** Use `np.linalg.eig(A)`

In [16]:
# YOUR CODE HERE


# Expected output:
# Eigenvalues: [3. 1.]
# Contains 3: True
# Contains 1: True

### Solution

```python
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Contains 3: {np.isclose(eigenvalues, 3).any()}")
print(f"Contains 1: {np.isclose(eigenvalues, 1).any()}")
```

---
### Exercise 16: Verify eigenvector equation

Using the same matrix `A = [[2,1],[1,2]]`, verify that `A @ v = lambda * v` for each eigenpair.

**Hint:** `eigenvectors[:, i]` gives the i-th eigenvector (column)

In [17]:
# YOUR CODE HERE


# Expected output:
# Eigenvalue 3.0: A@v == lambda*v? True
# Eigenvalue 1.0: A@v == lambda*v? True

### Solution

```python
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    Av = A @ v
    lv = lam * v
    print(f"Eigenvalue {lam:.1f}: A@v == lambda*v? {np.allclose(Av, lv)}")
```

---
### Exercise 17: Eigenvalues of identity matrix

What are the eigenvalues of the identity matrix `I = [[1,0],[0,1]]`?

**Think before coding:** Identity doesn't change ANY vector. So every vector is an eigenvector with eigenvalue = ?

**Hint:** All eigenvalues should be the same number.

In [18]:
# YOUR CODE HERE


# Expected: both eigenvalues = 1.0
# Because I @ v = 1 * v for ALL vectors

### Solution

```python
I = np.eye(2)
eigenvalues, eigenvectors = np.linalg.eig(I)
print(f"Eigenvalues: {eigenvalues}")
print(f"Both equal 1.0: {np.allclose(eigenvalues, [1.0, 1.0])}")
print("Because I @ v = 1 * v for ALL vectors")
```

---
## Section 5: Real-World Challenges

### Exercise 18: Find the centroid of data points

Given 3 data points: `[1,2]`, `[3,5]`, `[5,8]`.

Find the centroid (center point) by computing the mean vector.

**Hint:** Stack them in a matrix and use `.mean(axis=0)`

In [19]:
# YOUR CODE HERE


# Expected output:
# Data points: [[1 2] [3 5] [5 8]]
# Centroid: [3. 5.]

### Solution

```python
points = np.array([[1,2],[3,5],[5,8]])
print(f"Data points: {points}")
centroid = points.mean(axis=0)
print(f"Centroid: {centroid}")
```

---
### Exercise 19: Who is most similar to Alice?

User movie ratings:
- Alice = [5, 1, 3]
- Bob   = [4, 2, 3]
- Carol = [1, 5, 4]

Compute the dot product of Alice with Bob and Alice with Carol.
Who is more similar to Alice (higher dot product)?

**Hint:** `np.dot(alice, bob)` vs `np.dot(alice, carol)`

In [20]:
# YOUR CODE HERE


# Expected output:
# Alice . Bob  = 29
# Alice . Carol = 18
# Most similar to Alice: Bob

### Solution

```python
alice = np.array([5, 1, 3])
bob   = np.array([4, 2, 3])
carol = np.array([1, 5, 4])

sim_bob   = np.dot(alice, bob)
sim_carol = np.dot(alice, carol)

print(f"Alice . Bob  = {sim_bob}")
print(f"Alice . Carol = {sim_carol}")
print(f"Most similar to Alice: {'Bob' if sim_bob > sim_carol else 'Carol'}")
```

---
### Exercise 20: SVD and reconstruction

1. Create a 5x5 random matrix: `np.random.seed(42); A = np.random.randn(5, 5)`
2. Compute SVD: `U, S, Vt = np.linalg.svd(A)`
3. Reconstruct: `A_reconstructed = U @ np.diag(S) @ Vt`
4. Verify: `np.allclose(A, A_reconstructed)` should be `True`

**This proves SVD is a perfect decomposition - no information lost!**

In [21]:
# YOUR CODE HERE


# Expected output:
# Original A:
# [[ 0.4967 ... ]]
# Singular values: [3.53 ... ]
# Reconstruction matches: True

### Solution

```python
np.random.seed(42)
A = np.random.randn(5, 5)

U, S, Vt = np.linalg.svd(A)

print(f"Original A:\n{A.round(4)}")
print(f"\nSingular values: {S.round(4)}")

A_reconstructed = U @ np.diag(S) @ Vt
print(f"\nReconstruction matches: {np.allclose(A, A_reconstructed)}")
```

---
## All Done!

If you completed all 20 exercises, you now have hands-on experience with:

| Skill | Exercises |
|-------|----------|
| Vectors | 1-5 |
| Matrices | 6-10 |
| Determinant & Inverse | 11-14 |
| Eigenvalues | 15-17 |
| Real-World | 18-20 |

### Next Steps:
1. Re-do exercises without looking at solutions
2. Change the numbers and predict results before running
3. Watch **3Blue1Brown: Essence of Linear Algebra** on YouTube
4. Try `02_linear_algebra_visual.ipynb` for geometric intuition